config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[create]
  resources :owner_registrations, only: %i[create]
  resources :renter_registrations, only: %i[create]
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root 'welcome#index'
  get :signup, to: 'welcome#index'
  get :login, to: 'welcome#index'
  get :boatz, to: 'welcome#index'
  get :joinrenters, to: 'welcome#index'
  resources :listings do
    resources :rentals, shallow: true
  end
  
  resources :renters
  resources :owners do
    resources :vessels do
      resources :listings, shallow: true
    end
  end
  resources :vessels do
    member do
      delete :delete_file
    end
  end
  resources :rentals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :vessel
  has_many :rentals

  validates :price, :avail_start, :avail_end, presence: true, eligibility: true
  validates :description, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if avail_end.blank? || avail_start.blank?

    errors.add(:avail_end, 'must be after the start date') if avail_end < avail_start
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:vessel_id, :price, :avail_start, :avail_end, :description)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vessel_id %>
    <%= form.text_field :vessel_id %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :avail_start %>
    <%= form.datetime_select :avail_start %>
  </div>

    <div class="field">
    <%= form.label :avail_end %>
    <%= form.datetime_select :avail_end %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Vessel</th>
      <th>Price</th>
      <th>Avail start</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.vessel_id %></td>
        <td><%= listing.price %></td>
        <td><%= listing.avail_start %></td>
        <td><%= listing.description %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vessel:</strong>
  <%= @listing.vessel_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Avail start:</strong>
  <%= @listing.avail_start %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>