config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[create]
  resources :owner_registrations, only: %i[create]
  resources :renter_registrations, only: %i[create]
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root 'welcome#index'
  get :signup, to: 'welcome#index'
  get :login, to: 'welcome#index'
  get :boatz, to: 'welcome#index'
  get :joinrenters, to: 'welcome#index'
  resources :listings do
    resources :rentals, shallow: true
  end
  
  resources :renters
  resources :owners do
    resources :vessels do
      resources :listings, shallow: true
    end
  end
  resources :vessels do
    member do
      delete :delete_file
    end
  end
  resources :rentals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vessel.rb
class Vessel < ApplicationRecord
  belongs_to :owner
  has_many_attached :images
  has_many :listings, dependent: :destroy
  has_many :rentals, through: :listings
  validates :location, presence: true
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: %i[ show edit update destroy ]

  # GET /vessels or /vessels.json
  def index
    @vessels = Vessel.all
  end

  # GET /vessels/1 or /vessels/1.json
  def show
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
  end

  # POST /vessels or /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to @vessel, notice: "Vessel was successfully created." }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1 or /vessels/1.json
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to @vessel, notice: "Vessel was successfully updated." }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1 or /vessels/1.json
  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to vessels_url, notice: "Vessel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_file
    file = ActiveStorage::Attachment.find(params[:id])
    file.purge
    redirect_back(fallback_location: request.referrer)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vessel_params
      params.require(:vessel).permit(:owner_id, :name, :location, :berths, images:[])
    end
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/vessels/_form.html.erb
<%= form_with(model: vessel) do |form| %>
  <% if vessel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
        <% vessel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.text_field :owner_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :berths %>
    <%= form.text_field :berths %>
  </div>

  <div class="field">
   <%= form.label :images %>
   <%= form.file_field :images, multiple: true %>
 </div>
  <strong>Attachments:</strong>
 <ul>
 <% vessel.images.each do |image| %>
   <li>
     <%= link_to image.filename, rails_blob_path(image, disposition: :attachment) %>
     <%= link_to 'Remove', delete_file_vessel_url(image.id), method: :delete, data: { confirm: 'Are you sure?' } %>
   </li>
 <% end %>
 </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vessels/edit.html.erb
<h1>Editing Vessel</h1>

<%= render 'form', vessel: @vessel %>

<%= link_to 'Show', @vessel %> |
<%= link_to 'Back', vessels_path %>

app/views/vessels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vessels</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Name</th>
      <th>Location</th>
      <th>Berths</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= vessel.owner_id %></td>
        <td><%= vessel.name %></td>
        <td><%= vessel.location %></td>
        <td><%= vessel.berths %></td>
        <td><%= link_to 'Show', vessel %></td>
        <td><%= link_to 'Edit', edit_vessel_path(vessel) %></td>
        <td><%= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vessel', new_vessel_path %>

app/views/vessels/new.html.erb
<h1>New Vessel</h1>

<%= render 'form', vessel: @vessel %>

<%= link_to 'Back', vessels_path %>

app/views/vessels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @vessel.owner_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @vessel.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @vessel.location %>
</p>

<p>
  <strong>Berths:</strong>
  <%= @vessel.berths %>
</p>

<% if @vessel.images.any? %>
   <h3>Attachments:</h3>
   <% @vessel.images.each do |image| %>
     <% if image.variable? %>
       <%= image_tag image.variant(resize: "400x400") %>
     <% elsif image.previewable? %>
       <%= image_tag image.preview(resize: "400x400"), rails_blob_path(image, disposition: :attachment) %>
     <% else %>
       <%= link_to image.filename, rails_blob_path(image, disposition: :attachment) %>
     <% end %>
   <% end %>
 <% end %>

<%= link_to 'Edit', edit_vessel_path(@vessel) %> |
<%= link_to 'Back', vessels_path %>