config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[create]
  resources :owner_registrations, only: %i[create]
  resources :renter_registrations, only: %i[create]
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root 'welcome#index'
  get :signup, to: 'welcome#index'
  get :login, to: 'welcome#index'
  get :boatz, to: 'welcome#index'
  get :joinrenters, to: 'welcome#index'
  resources :listings do
    resources :rentals, shallow: true
  end
  
  resources :renters
  resources :owners do
    resources :vessels do
      resources :listings, shallow: true
    end
  end
  resources :vessels do
    member do
      delete :delete_file
    end
  end
  resources :rentals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validates :start_date, :end_date, presence: true, availability: true
  validates :num_guests, presence: true
  validates_numericality_of :num_guests, on: :create, message: "is not a number"
  validate :end_date_after_start_date, :start_date_after_avail_start, :end_date_before_avail_end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, 'must be after the start date') if end_date < start_date
  end

  def start_date_after_avail_start
    return if end_date.blank? || start_date.blank?
    
    errors.add(:start_date, 'must be after avialability begins') if start_date < listing.avail_start
  end

  def end_date_before_avail_end
    return if end_date.blank? || start_date.blank?
    
    errors.add(:end_date, 'must be before avialability ends') if end_date > listing.avail_end
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: %i[ show edit update destroy ]

  # GET /rentals or /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1 or /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals or /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: "Rental was successfully created." }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1 or /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: "Rental was successfully updated." }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1 or /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: "Rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rental_params
      params.require(:rental).permit(:user_id, :listing_id, :start_time, :end_time, :num_guests)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_with(model: rental) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
        <% rental.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :listing_id %>
    <%= form.text_field :listing_id %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :num_guests %>
    <%= form.text_field :num_guests %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rentals</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Listing</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Num guests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.user_id %></td>
        <td><%= rental.listing_id %></td>
        <td><%= rental.start_time %></td>
        <td><%= rental.end_time %></td>
        <td><%= rental.num_guests %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rental.user_id %>
</p>

<p>
  <strong>Listing:</strong>
  <%= @rental.listing_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @rental.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @rental.end_time %>
</p>

<p>
  <strong>Num guests:</strong>
  <%= @rental.num_guests %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>